import {
  CircleDot,
  Flame,
  Droplet,
  Zap,
  Leaf,
  Snowflake,
  Swords,
  Skull,
  Mountain,
  Wind,
  Brain,
  Bug,
  Gem,
  Ghost,
  Sparkles,
  Moon,
  Shield,
  Sparkle,
  type LucideIcon,
} from 'lucide-react'
import type { PokemonType } from '@/lib/constants/typeColors'

export const TYPE_ICONS: Record<PokemonType, LucideIcon> = {
  normal: CircleDot,
  fire: Flame,
  water: Droplet,
  electric: Zap,
  grass: Leaf,
  ice: Snowflake,
  fighting: Swords,
  poison: Skull,
  ground: Mountain,
  flying: Wind,
  psychic: Brain,
  bug: Bug,
  rock: Gem,
  ghost: Ghost,
  dragon: Sparkles,
  dark: Moon,
  steel: Shield,
  fairy: Sparkle,
}
